version: "3.9"

services:

  mysql:
    image: dqmdz/mysql:5.7
    ports:
      - "3306:3306"
    volumes:
      - ./data:/var/lib/mysql
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - TZ=America/Argentina/Mendoza

#  docum:
#    build: .
#    ports:
#      - 8080:8080
#    deploy:
#      restart_policy:
#        condition: on-failure
#    environment:
#      APP_SERVER: mysql:3306
#      APP_DATABASE: docum
#      APP_USER: root
#      APP_PASSWORD: root
#      APP_ADD-PROPERTIES: "false"
#      APP_LOGGING: "off"
#      APP_LIVERELOAD_ENABLED: "false"
#      APP_LIVERELOAD_PORT: 35895
#      APP_OPEN-IN-VIEW: "false"
